apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-6
  namespace: argocd
spec:
  description: project-6 apps and infra
  sourceRepos:
    - https://github.com/adamlevi87/project-6-gitops.git
    - https://github.com/adamlevi87/project-6-app.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: external-secrets.io
      kind: SecretStore
    - group: external-secrets.io
      kind: ExternalSecret
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: networking.k8s.io
      kind: Ingress
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: "argoproj.io"
      kind: "Application"
    - group: "autoscaling"
      kind: "HorizontalPodAutoscaler"
  clusterResourceWhitelist: []
  orphanedResources:
    warn: true
